name: Dotnet Publish II
description: Create the packeged output for a .NET Core project.

branding:
  color: purple
  icon: package

inputs:
  path:
    description: Path to the project to publish.
    required: false
    default: .
  output-dir:
    description: Directory where all packages will be put (default value is 'packages').
    required: false
    default: packages
  build-configuration:
    description: Build configuration for the build (default value is 'Release').
    required: false
    default: Release
  skip-build:
    description: Whether to skip the build using the --no-build flag (default value is 'true').
    required: false
    default: "true"
  args:
    description: Any further args for dotnet publish.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create Nuget packages
      uses: EasyDesk/action-dotnet@v1
      with:
        script: |
          ARGS=${{ inputs.args }}
          if [[ '${{ inputs.skip-build }}' == "true" ]] ; then
            ARGS="${ARGS} --no-build"
          fi
          echo '${{ inputs.path }}' | while read P ; do
            if [ -z "${P}" ] ; then
              continue
            fi
            dotnet publish "${P}" -o '${{ inputs.output-dir }}' -c '${{ inputs.build-configuration }}' ${ARGS}
          done
